### ISSUE TITLE
Falta de espaço no PDF

### ISSUE THREAD

**Issue by he7d3r** [livroscolaborativos/CalculoNumerico#128]
Na página "iv" do PDF mais recente, aparece a frase "escrito em código LaTeXdisponível", onde deveria haver um espaço entre o código "LaTeX" e a palavra "disponível". O problema não ocorre na versão HTML disponível em https://www.ufrgs.br/numerico/, e aparece um espaço no código TeX:
https://github.com/livroscolaborativos/CalculoNumerico/blob/0a4631f88ada5d69bf9ce81a8487ada265db4af7/nota_organizadores.tex#L13

A solução é trocar `\LaTeX` por `\LaTeX{}`.

**Comment by phkonzen** [comment]
Helder,
obrigado por sua colaboração. No Merge #131 busquei fazer as correções sugeridas.
Pedro.
