### ISSUE TITLE
Arredondamento conforme a ABNT

### ISSUE THREAD

**Issue by he7d3r** [livroscolaborativos/CalculoNumerico#157]
Acredito que seria interessante que a seção da página 13 sobre arredondamento também mencionasse norma NBR 5891 de 2014 da ABNT (ou a [resolução 886/66 da Fundação IBGE](https://pir2.forumeiros.com/t5114-arredondamento-de-numeros-res-886-de-06-10-66-ibge)), onde, ao fazer o arredondamento, é considerada a paridade do último algarismo a ser conservado para decidir se deve ou não ser incrementado.

**Comment by phkonzen** [comment]
Olá,

No #169 foi adicionado comentários sobre o arredondamento por proximidade com desempate par. Certamente, ainda pode-se dissertar muito mais sobre o assunto, mas acredito que isto é suficiente para um conteúdo de introdução sobre cálculo numérico. 

Como sugestão, caso haja demanda para discutir sobre outras regras de arredondamento, isto poderia ser feito em um seção específica ou como anexo.

Pedro
