### ISSUE TITLE
Manter o PDF no GitHub?

### ISSUE THREAD

**Issue by phkonzen** [livroscolaborativos/CalculoNumerico#184]
O arquivo PDF da versão Scilab foi inicialmente mantido no GitHub. Entretanto, seu controle de versão causa a necessidade resolver conflitos a cada fusão. Além disso, não há motivo para priorizar a versão Scilab frente as outras (Octave e Python).

Desta forma, sugiro descontinuar o controle de versão do main.pdf.

**Comment by lfguidi** [comment]
Concordo com a proposta.

---
Leonardo Fernandes Guidi
tel.+55(51)3308-6205
guidi@mat.ufrgs.br

Em 07/11/2017 10:29, Pedro Konzen escreveu:

**Comment by he7d3r** [comment]
Concordo com a remoção (lembrando que há a [opção de criar releases](https://github.com/livroscolaborativos/CalculoNumerico/issues/129#issuecomment-293991000) para esses arquivos).

**Comment by phkonzen** [comment]
Isso é bom lembrar, no lançamento podemos incluir as três versões no formato PDF.

**Comment by phkonzen** [comment]
Após esta consulta ficou decidido descontinuar o controle do arquivo main.pdf. Isto será feito em breve, concomitante com a reformulação do site www.ufrgs.br/numerico que está em curso.
