### ISSUE TITLE
Formato EPUB

### ISSUE THREAD

**Issue by phkonzen** [livroscolaborativos/CalculoNumerico#185]
O formato EPUB não fica bem compilado com vários problemas de formatação. Até o momento, não encontramos nenhum desenvolvedor para trabalhar na compilação deste formato. Além disso, o processo de compilação atual demanda quase uma hora para gerar o EPUB.

Assim, recomendo que o formato EPUB não seja mais disponibilizado no site do livro (www.ufrgs.br/numerico).

**Comment by lfguidi** [comment]
Concordo com a proposta.

---
Leonardo Fernandes Guidi
tel.+55(51)3308-6205
guidi@mat.ufrgs.br

Em 07/11/2017 10:35, Pedro Konzen escreveu:
