### ISSUE TITLE
Release 2017?

### ISSUE THREAD

**Issue by phkonzen** [livroscolaborativos/CalculoNumerico#187]
O GitHub permite que façamos um lançamento de uma versão. Que tal fazermos o lançamento da versão atual como versão 2017?

**Comment by Esequia** [comment]
Eu apoio!

2017-11-07 13:12 GMT-02:00 Pedro Konzen <notifications@github.com>:

**Comment by lfguidi** [comment]
Também concordo com a proposta.

---
Leonardo Fernandes Guidi
tel.+55(51)3308-6205
guidi@mat.ufrgs.br

Em 07/11/2017 13:12, Pedro Konzen escreveu:

**Comment by he7d3r** [comment]
Concordo, mas talvez possam ser feitas releases semestrais (antes do início de cada semestre letivo)?

**Comment by djusto** [comment]
Uma versão estável ao inicio de cada semestre letivo é uma boa opção.

at.

dago

**Comment by phkonzen** [comment]
Lançamentos semestrais parece mesmo uma boa.

**Comment by fazedo** [comment]
Excelente, podemos ter versões estáveis em cada semestre de forma que o professor possa citar número de página e de teoremas. Podemos aproveitar o ânimo para fazer uma revisão do texto para lançar a primeira versão para o início do próximo semestre.

**Comment by phkonzen** [comment]
Poderíamos fazer uma versão em janeiro e outra em junho a cada ano.
