### ISSUE TITLE
Usar \[\] (LaTeX) em vez de  $$ (TeX)

### ISSUE THREAD

**Issue by he7d3r** [livroscolaborativos/CalculoNumerico#206]
Considerando que o livro é escrito em LaTeX, e que `$$ ... $$` é uma sintaxe primitiva do TeX, não suportada oficialmente pelo LaTeX,² e que é recomendado o uso de `\[ ... \]` em vez de pares de símbolos de dólar para delimitar as fórmulas,³ gostaria de sugerir a atualização desta sintaxe nos lugares em que ela é utilizada, e a inclusão de uma observação a respeito na folha de estilos.

¹ https://github.com/livroscolaborativos/CalculoNumerico/blob/master/FOLHA_DE_ESTILO.md#c%C3%B3digo-fonte-latex
² https://tex.stackexchange.com/a/69854/25761
³ https://ctan.org/tex-archive/info/l2tabu/english/

**Comment by fazedo** [comment]
Olá, Helder. 

Você tem razão, obrigado pela sugestão. Eu iria além, acho que deveríamos usar apenas equações numeradas, o que facilitaria a localização aquando de envio de sugestões e correções.
