### ISSUE TITLE
Release 2018.1

### ISSUE THREAD

**Issue by phkonzen** [livroscolaborativos/CalculoNumerico#210]
Tendo em vista o lançamento (veja os Issues #129 #184 #187) da primeira versão do "Cálculo Numérico - Um Livro Colaborativo", peço que todos os colaboradores enviem suas contribuições ao projeto até no máximo dia **14.01.2018**. Na semana que inicia no dia 15.01.2018 será efetivado o lançamento da versão 2018.1.

Sugestão de registro do lançamento:
Tag: v2018.1
Título: Cálculo Numérico - Um Livro Colaborativo - v2018.1
Binários a serem incluídos: todas as versões em PDF

**Comment by livroscolaborativos** [comment]
O _release_ v2018.1 já está disponível!
