### ISSUE TITLE
Uso de i-ésimo ou $i$-ésimo

### ISSUE THREAD

**Issue by fazedo** [livroscolaborativos/CalculoNumerico#211]
Qual nomenclatura é melhor? i-ésimo ou $i$-ésimo? Acho que devemos padronizar.

**Comment by lfguidi** [comment]
Boa tarde.

Se for para votar, escolho a segunda opção.

Abraços,
---
Leonardo Fernandes Guidi
tel.+55(51)3308-6205
guidi@mat.ufrgs.br

Em 03/01/2018 13:25, Fabio Souto de Azevedo escreveu:

**Comment by phkonzen** [comment]
Também acho melhor $i$-ésimo.

**Comment by Esequia** [comment]
Também acho melhor $i$-ésimo.

2018-01-03 15:51 GMT-02:00 Pedro Konzen <notifications@github.com>:

**Comment by he7d3r** [comment]
Também considero que é mais apropriado escrever "$i$-ésimo".
