### ISSUE TITLE
Erro de digitação na descrição dos repositórios do GitHub

### ISSUE THREAD

**Issue by he7d3r** [livroscolaborativos/CalculoNumerico#217]
Atualmente está escrito
> Escrita colaborativa de recursos educacioais abertos sobre...

mas deveria ser
> Escrita colaborativa de recursos **educacionais** abertos sobre...

O mesmo problema se repete em todos os repositórios
* https://github.com/reamat/AlgebraLinear
* https://github.com/reamat/Calculo
* https://github.com/reamat/CalculoNumerico
* https://github.com/reamat/ComputacaoCientifica
* https://github.com/reamat/TransformadasIntegrais

**Comment by phkonzen** [comment]
corrigido
