### ISSUE TITLE
Resposta dos exercícios

### ISSUE THREAD

**Issue by fazedo** [livroscolaborativos/CalculoNumerico#75]
Acabei de notar que as respostas dos exercícios não estão aparecendo no .pdf final.

**Comment by phkonzen** [comment]
Olá Fabio,
O último merge deve ter resolvido isso. Por favor, verifique.
Abs.,
Pedro.

**Comment by fazedo** [comment]
Olá, Pedro.

Está funcionando, obrigado.

Abs,
Fabio
