### ISSUE TITLE
title verbatim nos exercícios na versão html

### ISSUE THREAD

**Issue by fazedo** [livroscolaborativos/CalculoNumerico#95]
A marcação title= está aparecendo verbatim nos exercícios na versão html. Exemplo https://www.ufrgs.br/numerico/livro/sdeduv-exercicios_finais.html

Abraços,
Fabio

**Comment by phkonzen** [comment]
O tag "title" nos ambientes de exercícios não é suportado em todos os formatos. Portanto, não deve ser usado. Estes tags foram removidos do código fonte.
